[build]
builder = "nixpacks"
buildCommand = "chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/*.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
